- name: Install MariaBb server
  ansible.builtin.apt:
    name: mariadebe-server
    state: present
    update_cache: yes

- name: Iniciar y habilitar servicio
  ansible.builtin.systemd:
  name: mariadb
  state: started
  enable: yes

- name: Iniciar y habilitar servicio
  ansible.builtin.mysql_user:
  name: root 
  password: "{{wordpress_db_password}}"
  host: localhost

- name: configurar contraseña root para mariadb

- name: 

- name: Crear DB para wordpress

- name: crear usuario de bbdd para wordpress


