#SPDX-License-Identifier: MIT-0
---
# handlers file for nginx
#SPDX-License-Identifier: MIT-0
---
# handlers file for nginx
- name: Reiniciar Nginx
  ansible.builtin.service:
    name: nginx #Nombre del servicio a reiniciar
    state: restarted #Reinicia el servicio
  when: ansible_facts.services['nginx.service'].state == 'running' #Solo si el servicio está corriendo
  #when: ansible_facts.services['nginx'].state == 'running' #Condición para versiones antiguas